[profile.default]
src = "."
out = "out"
libs = ["node_modules", "lib"]
remappings = [
    "@coti-io/=node_modules/@coti-io/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat/=node_modules/hardhat/",
    "forge-std/=lib/forge-std/src/"
]
solc = "0.8.19"
optimizer = true
optimizer_runs = 1

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
